[package]
name = "sharc"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["jit"]
jit = [
    "dep:cranelift-jit",
    "dep:cranelift-codegen",
    "dep:cranelift-frontend",
    "dep:cranelift-module",
    "dep:cranelift-native",
]

[dependencies]
serde = { workspace = true }
cranelift-jit = { workspace = true, optional = true }
cranelift-codegen = { workspace = true, optional = true }
cranelift-frontend = { workspace = true, optional = true }
cranelift-module = { workspace = true, optional = true }
cranelift-native = { workspace = true, optional = true }
